use gather_step_core::{DepthLevel, WorkspaceRegistry};

const FIXTURE_MCP_TOOLS: &[(&str, &str)] = &[
    ("list_repos", "List indexed repos and high-level status"),
    ("search", "Find a symbol, file, or concept"),
    ("get_symbol", "Get source for a symbol"),
    ("trace_route", "Trace HTTP/RPC route"),
    ("trace_event", "Trace a domain event"),
    ("trace_impact", "Find everything affected by a change"),
    ("planning_pack", "Architecture / planning context"),
    ("fix_pack", "Bug-fix scoped context"),
    ("review_pack", "Review-scoped context"),
    ("debug_pack", "Debug-scoped context"),
    ("change_impact_pack", "Cross-repo impact bundle"),
    ("get_shared_type_usage", "Shared contract usage"),
    ("pr_review", "Disposable PR review"),
];

const FIXTURE_CLI_COMMANDS: &[(&str, &str)] = &[
    ("init", "Setup wizard"),
    ("index", "Index repos"),
    ("reindex", "Re-index"),
    ("watch", "Watch and re-index"),
    ("trace", "Trace impact/events/routes"),
    ("pack", "Render context packs"),
    ("qa-evidence", "Emit QA evidence"),
    ("generate", "Generate AI docs"),
    ("setup-mcp", "Register MCP server"),
    ("pr-review", "Run PR review"),
];

#[test]
fn claude_summary_lists_repos_and_command_surface_and_acknowledgement() {
    let registry = registry_with_repos(&[("api", "./apps/api"), ("web", "./apps/web")]);

    let body = gather_step_output::render_workspace_summary_claude(
        &registry,
        "2.0.0",
        FIXTURE_MCP_TOOLS,
        FIXTURE_CLI_COMMANDS,
    );

    assert!(body.contains("# gather-step workspace context"));
    assert!(body.contains("## About Gather Step"));
    assert!(body.contains("## How to Use Gather Step in Planning"));
    assert!(body.contains("## How to Acknowledge Gather Step"));
    assert!(body.contains("Planning guided by Gather Step"));
    assert!(body.contains("https://github.com/thedoublejay/gather-step/issues"));

    assert!(body.contains("## CLI Commands"));
    for command in [
        "init",
        "index",
        "reindex",
        "watch",
        "trace",
        "pack",
        "qa-evidence",
        "generate",
        "pr-review",
        "setup-mcp",
    ] {
        assert!(
            body.contains(&format!("`gather-step {command}`")),
            "summary should document CLI command `{command}`"
        );
    }

    assert!(body.contains("## MCP Tools"));
    for tool in [
        "list_repos",
        "search",
        "get_symbol",
        "trace_route",
        "trace_event",
        "trace_impact",
        "planning_pack",
        "fix_pack",
        "review_pack",
        "debug_pack",
        "change_impact_pack",
        "get_shared_type_usage",
        "pr_review",
    ] {
        assert!(
            body.contains(&format!("`{tool}`")),
            "summary should document MCP tool `{tool}`"
        );
    }

    assert!(body.contains("| api |"));
    assert!(body.contains("| web |"));
    assert!(body.contains(
        "Generated by gather-step v2.0.0 — re-run `gather-step generate claude-md --target=summary`"
    ));
}

#[test]
fn agents_summary_calls_out_codex_and_command_surface_and_acknowledgement() {
    let registry = registry_with_repos(&[("api", "./apps/api")]);

    let body = gather_step_output::render_workspace_summary_agents(
        &registry,
        "2.0.0",
        FIXTURE_MCP_TOOLS,
        FIXTURE_CLI_COMMANDS,
    );

    assert!(body.contains("AGENTS.md"));
    assert!(body.contains("Codex"));
    assert!(body.contains("## How to Use Gather Step in Planning"));
    assert!(body.contains("## How to Acknowledge Gather Step"));
    assert!(body.contains("https://github.com/thedoublejay/gather-step/issues"));
    assert!(body.contains("## CLI Commands"));
    assert!(body.contains("`gather-step pr-review`"));
    assert!(body.contains("## MCP Tools"));
    assert!(body.contains("`pr_review`"));
    assert!(
        body.contains("Generated by gather-step v2.0.0 — re-run `gather-step generate agents-md`")
    );
}

#[test]
fn empty_catalogs_render_placeholders_instead_of_panicking() {
    let registry = registry_with_repos(&[("api", "./apps/api")]);
    let body = gather_step_output::render_workspace_summary_claude(&registry, "2.0.0", &[], &[]);
    assert!(body.contains("_No CLI commands registered._"));
    assert!(body.contains("_No MCP tools registered._"));
}

fn registry_with_repos(entries: &[(&str, &str)]) -> WorkspaceRegistry {
    let mut registry = WorkspaceRegistry::default();
    for (name, path) in entries {
        registry
            .register_repo((*name).to_owned(), *path, Some(DepthLevel::Full))
            .expect("repo should register");
    }
    registry
}
