use gather_step_core::{DepthLevel, WorkspaceRegistry};

#[test]
fn claude_summary_lists_repos_and_includes_mcp_pointer() {
    let registry = registry_with_repos(&[("api", "./apps/api"), ("web", "./apps/web")]);

    let body = gather_step_output::render_workspace_summary_claude(&registry, "1.0.0");

    assert!(body.contains("# gather-step workspace context"));
    assert!(body.contains("| api |"));
    assert!(body.contains("| web |"));
    assert!(body.contains("gather-step mcp serve"));
    assert!(body.contains(
        "Generated by gather-step v1.0.0 — re-run `gather-step generate claude-md --target=summary`"
    ));
}

#[test]
fn agents_summary_calls_out_codex_and_handcrafted_agents_md() {
    let registry = registry_with_repos(&[("api", "./apps/api")]);

    let body = gather_step_output::render_workspace_summary_agents(&registry, "1.0.0");

    assert!(body.contains("AGENTS.md"));
    assert!(body.contains("Codex"));
    assert!(body.contains("gather-step mcp serve"));
    assert!(
        body.contains("Generated by gather-step v1.0.0 — re-run `gather-step generate agents-md`")
    );
}

fn registry_with_repos(entries: &[(&str, &str)]) -> WorkspaceRegistry {
    let mut registry = WorkspaceRegistry::default();
    for (name, path) in entries {
        registry
            .register_repo((*name).to_owned(), *path, Some(DepthLevel::Full))
            .expect("repo should register");
    }
    registry
}
