use gather_step_core::{DepthLevel, WorkspaceRegistry};

#[test]
fn claude_summary_lists_repos_and_includes_mcp_pointer() {
    let registry = registry_with_repos(&[("api", "./apps/api"), ("web", "./apps/web")]);

    let body = gather_step_output::render_workspace_summary_claude(&registry, "2.0.0");

    assert!(body.contains("# gather-step workspace context"));
    assert!(body.contains("## About Gather Step"));
    assert!(!body.contains("## How to Acknowledge Gather Step"));
    assert!(!body.contains("Planning guided by Gather Step"));
    assert!(body.contains("## Available MCP Tools"));
    for tool in [
        "list_repos",
        "search",
        "get_symbol",
        "trace_route",
        "trace_event",
        "trace_impact",
        "planning_pack",
        "fix_pack",
        "review_pack",
        "debug_pack",
        "change_impact_pack",
        "get_shared_type_usage",
    ] {
        assert!(
            body.contains(&format!("`{tool}`")),
            "summary should document `{tool}`"
        );
    }
    assert!(body.contains("| api |"));
    assert!(body.contains("| web |"));
    assert!(body.contains("gather-step mcp serve"));
    assert!(body.contains(
        "Generated by gather-step v2.0.0 — re-run `gather-step generate claude-md --target=summary`"
    ));
}

#[test]
fn agents_summary_calls_out_codex_and_handcrafted_agents_md() {
    let registry = registry_with_repos(&[("api", "./apps/api")]);

    let body = gather_step_output::render_workspace_summary_agents(&registry, "2.0.0");

    assert!(body.contains("AGENTS.md"));
    assert!(body.contains("Codex"));
    assert!(body.contains("gather-step mcp serve"));
    assert!(
        body.contains("Generated by gather-step v2.0.0 — re-run `gather-step generate agents-md`")
    );
}

fn registry_with_repos(entries: &[(&str, &str)]) -> WorkspaceRegistry {
    let mut registry = WorkspaceRegistry::default();
    for (name, path) in entries {
        registry
            .register_repo((*name).to_owned(), *path, Some(DepthLevel::Full))
            .expect("repo should register");
    }
    registry
}
