pub mod ai_typescript;
pub mod azure;
pub mod detect;
pub mod drizzle;
pub mod fastapi;
pub mod frontend_hooks;
pub mod frontend_react;
pub mod frontend_router;
pub mod gateway_proxy;
pub mod local_config;
pub mod migration_utils;
pub mod mongo;
pub mod mongo_safety;
pub mod mongoose;
pub mod mongoose_migration;
pub mod nestjs;
pub mod nextjs;
pub mod prisma;
pub mod profile;
pub mod python_kafka;
pub mod registry;
pub mod storybook;
pub mod tailwind;
pub mod typeorm;
pub mod typeorm_migration;

pub use detect::{Framework, detect_frameworks, detect_frameworks_workspace_aware};
