use std::{cmp::Ordering, collections::BTreeSet, fmt::Write as _, path::PathBuf};

use chrono::{SecondsFormat, Utc};
use gather_step_analysis::{cross_repo_deps, list_orphan_topics, trace_event, trace_route};
use gather_step_core::{NodeKind, RegisteredRepo, WorkspaceRegistry};
use gather_step_storage::{GraphStore, GraphStoreDb, MetadataStore};
use thiserror::Error;

use crate::sanitize::{sanitize_table_cell, wrap_inline_code};

const DEFAULT_LIMIT: usize = 32;

/// Per-file byte budget for generated rule files. Roughly four bytes per
/// token for markdown tables, so this is ~4,000 tokens — enough to load into
/// a Claude Code session without dominating the context window.
pub const DEFAULT_RULE_BYTE_BUDGET: usize = 16_000;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuleFile {
    pub relative_path: String,
    pub content: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ClaudeMdOptions {
    pub repo_filter: Option<String>,
    /// Maximum bytes per generated rule file. `None` disables the cap;
    /// `Some(n)` truncates content over `n` bytes at the last preceding
    /// newline and appends a `<!-- Truncated: ... -->` marker. The default
    /// (via `Default::default()`) is `Some(DEFAULT_RULE_BYTE_BUDGET)`.
    pub byte_budget: Option<usize>,
    /// Workspace root used to relativize absolute repo paths in generated
    /// output.  When `Some`, absolute paths inside the workspace are rendered
    /// as workspace-relative strings; paths outside the workspace are replaced
    /// with the `"<outside-workspace>"` sentinel.  When `None`, the absolute
    /// path is used as-is (preserves backward compatibility).
    pub workspace_root: Option<PathBuf>,
}

impl Default for ClaudeMdOptions {
    fn default() -> Self {
        Self {
            repo_filter: None,
            byte_budget: Some(DEFAULT_RULE_BYTE_BUDGET),
            workspace_root: None,
        }
    }
}

#[derive(Debug, Error)]
pub enum ContextMdError {
    #[error(transparent)]
    Graph(#[from] gather_step_storage::GraphStoreError),
    #[error(transparent)]
    Metadata(#[from] gather_step_storage::MetadataStoreError),
    #[error(transparent)]
    Query(#[from] gather_step_analysis::QueryError),
    #[error(transparent)]
    CrossRepo(#[from] gather_step_analysis::CrossRepoError),
    #[error(transparent)]
    EventTopology(#[from] gather_step_analysis::EventTopologyError),
}

pub fn generate_rule_files(
    graph: &GraphStoreDb,
    metadata: Option<&dyn MetadataStore>,
    registry: &WorkspaceRegistry,
    options: &ClaudeMdOptions,
) -> Result<Vec<RuleFile>, ContextMdError> {
    let repo_names = selected_repo_names(registry, options.repo_filter.as_deref());
    let budget = options.byte_budget;
    let mut files = vec![
        RuleFile {
            relative_path: ".claude/rules/gather-step-architecture.md".to_owned(),
            content: apply_budget(
                render_architecture_rule(graph, metadata, registry, &repo_names)?,
                budget,
            ),
        },
        RuleFile {
            relative_path: ".claude/rules/gather-step-events.md".to_owned(),
            content: apply_budget(render_events_rule(graph, &repo_names)?, budget),
        },
        RuleFile {
            relative_path: ".claude/rules/gather-step-routes.md".to_owned(),
            content: apply_budget(render_routes_rule(graph, &repo_names)?, budget),
        },
    ];

    if let Some(repo) = options.repo_filter.as_deref()
        && let Some(registered) = registry.repo(repo)
    {
        files.push(RuleFile {
            relative_path: format!(".claude/rules/gather-step-repo-{repo}.md"),
            content: apply_budget(
                render_repo_rule(graph, repo, registered, options.workspace_root.as_deref())?,
                budget,
            ),
        });
    }

    Ok(files)
}

pub fn render_workspace_summary_claude(registry: &WorkspaceRegistry, version: &str) -> String {
    let mut body = String::new();
    body.push_str("# gather-step workspace context\n\n");
    let _ = writeln!(
        body,
        "> Generated by gather-step v{version} — re-run `gather-step generate claude-md --target=summary` to refresh.\n"
    );
    body.push_str(workspace_summary_reference_block());
    push_workspace_summary_repos(&mut body, registry);
    body.push_str("## How to use gather-step with AI tools\n\n");
    body.push_str(
        "gather-step exposes a code graph over MCP. Point your AI tool at the MCP server for cross-repo dependency tracing, symbol search, file ownership, and hotspot analysis.\n\n",
    );
    body.push_str("MCP server: `gather-step mcp serve`\n");
    body.push_str("Re-index: `gather-step reindex`\n");
    body.push_str("Watch mode: `gather-step watch`\n");
    body
}

fn workspace_summary_reference_block() -> &'static str {
    r"## About Gather Step

Gather Step is a local-first code graph tool that indexes your workspace and exposes a semantic graph over symbols, routes, events, and cross-repo edges. When Gather Step is registered as an MCP server, these capabilities are available via MCP tool calls.

Use Gather Step tools before reasoning about cross-repo impact, tracing a request path, or planning a refactor. Gather Step surfaces edges between services, contract ownership, and downstream breakage from type changes.

## Available MCP Tools

| Tool | Purpose |
|------|---------|
| `get_graph_schema` | Inspect graph node and edge schema |
| `get_graph_schema_summary` | Get a compact graph schema overview |
| `list_repos` | List indexed repos and high-level status |
| `search` | Find a symbol, file, or concept |
| `get_symbol` | Get source, location, and graph edges for a symbol |
| `get_callers` | Find callers for a known symbol |
| `get_callees` | Find callees for a known symbol |
| `trace_impact` | Find everything affected by changing a symbol or file |
| `trace_event` | Trace a domain event from producer to consumers |
| `trace_route` | Trace an HTTP or RPC route from entry to handler |
| `crud_trace` | Trace CRUD-style request paths |
| `event_blast_radius` | Inspect downstream event impact |
| `list_orphan_topics` | Find event topics without linked producers or consumers |
| `cross_repo_deps` | Inspect cross-repo dependency edges |
| `get_shared_type_usage` | Find all usages of a shared contract type |
| `payload_schema` | Inspect inferred payload schema evidence |
| `contract_drift` | Find contract drift signals |
| `projection_impact` | Trace source, projected field, filter, index, and backfill evidence |
| `where_deployed` | Find deployments for an indexed service |
| `service_env` | List env vars consumed by an indexed service |
| `env_var_consumers` | Find services that consume an env var |
| `undeployed_services` | Find indexed services without deployment evidence |
| `deployed_but_no_code` | Find deployment nodes without service-code linkage |
| `shared_infra` | Find databases and brokers with service consumers |
| `breaking_change_candidates` | Surface likely breaking-change risks |
| `brief` | Get a compact orientation response |
| `context` | Get bounded context for a target |
| `context_pack` | Get a task-shaped context pack |
| `get_context_pack` | Alias for task-shaped context packs |
| `planning_pack` | Context pack for architecture and planning tasks |
| `plan_change` | Alias for planning-oriented context |
| `debug_pack` | Context pack for debugging production issues |
| `fix_pack` | Context pack scoped for a bug fix |
| `fix_surface` | Get a narrower fix-oriented surface |
| `review_pack` | Context pack scoped for code review |
| `change_impact_pack` | Cross-repo change impact bundle |
| `get_change_impact_pack` | Alias for change impact context |
| `batch_query` | Run multiple read-only graph queries together |
| `who_owns` | Find ownership evidence for a file or symbol |
| `get_dead_code` | Surface dead-code candidates |
| `get_conventions` | Summarize detected workspace conventions |
| `get_overview` | Get a high-level workspace overview |

"
}

pub fn render_workspace_summary_agents(registry: &WorkspaceRegistry, version: &str) -> String {
    let mut body = String::new();
    body.push_str("# gather-step workspace context for Codex\n\n");
    let _ = writeln!(
        body,
        "> Generated by gather-step v{version} — re-run `gather-step generate agents-md` to refresh.\n"
    );
    body.push_str("## Workspace graph\n\n");
    body.push_str(
        "gather-step indexes this workspace and exposes cross-repo code intelligence over MCP.\n\n",
    );
    body.push_str("MCP server: `gather-step mcp serve`\n");
    body.push_str("Re-index: `gather-step reindex`\n");
    body.push_str("Watch mode: `gather-step watch`\n\n");
    push_workspace_summary_repos(&mut body, registry);
    body.push_str("## Agent guidance\n\n");
    body.push_str(
        "- Use gather-step MCP before broad file searches when tracing cross-repo ownership or dependencies.\n",
    );
    body.push_str(
        "- Treat this file as generated context. Put durable human preferences in `AGENTS.md`.\n",
    );
    body
}

fn push_workspace_summary_repos(body: &mut String, registry: &WorkspaceRegistry) {
    body.push_str("## Repos in this workspace\n\n");
    body.push_str("| Name | Path |\n|---|---|\n");
    if registry.repos.is_empty() {
        body.push_str("| _No registered repos found_ | - |\n\n");
        return;
    }

    for (name, repo) in &registry.repos {
        let _ = writeln!(
            body,
            "| {} | {} |",
            sanitize_table_cell(name),
            sanitize_table_cell(&repo.path.display().to_string())
        );
    }
    body.push('\n');
}

/// Truncate `content` to `budget` bytes (rounded down to the last newline) and
/// append a `<!-- Truncated: ... -->` marker that documents how much was cut.
/// `None` disables the cap.
fn apply_budget(content: String, budget: Option<usize>) -> String {
    let Some(budget) = budget else { return content };
    if content.len() <= budget {
        return content;
    }

    let original_len = content.len();
    // Truncate at the last newline within budget so we never split a markdown
    // table row mid-line; if there is no newline within the budget (very small
    // budget) fall back to a hard cut at the budget boundary.
    let cut_at = content[..budget].rfind('\n').map_or(budget, |idx| idx + 1);
    let removed = original_len - cut_at;
    // Approximate: GPT/Claude tokenizers average ~4 bytes per token for
    // English markdown. This figure is informational only.
    let approx_tokens = removed / 4;

    let mut out = String::with_capacity(cut_at + 256);
    out.push_str(&content[..cut_at]);
    let _ = write!(
        out,
        "\n<!-- Truncated: removed {removed} bytes (~{approx_tokens} tokens) to stay within the {budget}-byte budget. \
Reduce repo scope, raise ClaudeMdOptions.byte_budget, or generate per-repo files. -->\n",
    );
    out
}

pub fn derive_conventions(
    graph: &GraphStoreDb,
    registry: &WorkspaceRegistry,
    repo_filter: Option<&str>,
) -> Result<Vec<String>, ContextMdError> {
    let repo_names = selected_repo_names(registry, repo_filter);
    let mut conventions = BTreeSet::new();

    for repo_name in &repo_names {
        if let Some(repo) = registry.repo(repo_name) {
            for framework in &repo.frameworks {
                conventions.insert(match framework.as_str() {
                    "nestjs" => {
                        "NestJS repos expose HTTP and messaging surfaces through framework decorators."
                    }
                    "react" => "React repos centralize UI state and endpoint usage in component trees.",
                    "react_router" => "Frontend routing is modeled through React Router conventions.",
                    "nextjs" => "Next.js repos likely use file-based routes and server/client boundaries.",
                    "storybook" => "Storybook is present for component-driven UI validation.",
                    "prisma" => "Database contracts are likely defined through Prisma schema artifacts.",
                    "drizzle" => "Database access patterns include Drizzle configuration and generated SQL types.",
                    "mongoose" => "MongoDB models are represented through Mongoose schemas and entities.",
                    "azure" => "Azure messaging or realtime SDKs are part of the integration surface.",
                    _ => continue,
                });
            }
        }
    }

    if !graph.nodes_by_type(NodeKind::Route)?.is_empty() {
        conventions
            .insert("HTTP APIs are normalized into virtual Route nodes for cross-repo tracing.");
    }
    if !event_targets(graph, &repo_names)?.is_empty() {
        conventions.insert("Event integrations are normalized into virtual event/topic nodes with producer and consumer edges.");
    }
    if !graph.nodes_by_type(NodeKind::SharedSymbol)?.is_empty() {
        conventions.insert("Cross-repo contracts are represented as versioned SharedSymbol nodes.");
    }
    if !graph.nodes_by_type(NodeKind::PayloadContract)?.is_empty() {
        conventions.insert("Payload contracts are inferred from producer and consumer call sites.");
    }

    Ok(conventions.into_iter().map(str::to_owned).collect())
}

fn render_architecture_rule(
    graph: &GraphStoreDb,
    metadata: Option<&dyn MetadataStore>,
    registry: &WorkspaceRegistry,
    repo_names: &[String],
) -> Result<String, ContextMdError> {
    let mut out = String::new();
    write_header(&mut out, "Architecture");
    out.push_str("# Codebase Intelligence\n\n");
    out.push_str("## Repository Map\n");
    out.push_str("| Repo | Frameworks | Files | Symbols | Depth | Routes | Topics |\n");
    out.push_str("|---|---|---:|---:|---|---:|---:|\n");
    let mut repo_rows = 0_usize;
    for repo_name in repo_names {
        if let Some(repo) = registry.repo(repo_name) {
            let (routes, topics) = count_virtual_surfaces(graph, repo_name)?;
            let _ = writeln!(
                out,
                "| {repo} | {frameworks} | {files} | {symbols} | {depth} | {routes} | {topics} |",
                repo = sanitize_table_cell(repo_name),
                frameworks = if repo.frameworks.is_empty() {
                    "-".to_owned()
                } else {
                    // Framework names come from user-authored workspace config.
                    sanitize_table_cell(&repo.frameworks.join(", "))
                },
                files = repo.file_count,
                symbols = repo.symbol_count,
                depth = depth_label(repo.depth_level), // literal — sanitization unnecessary
            );
            repo_rows += 1;
        }
    }
    if repo_rows == 0 {
        out.push_str("| _No registered repos found_ | - | - | - | - | - | - |\n");
        out.push_str(
            "\nIndex a workspace first with `gather-step init` and `gather-step index` to populate repository metadata.\n",
        );
    }

    out.push_str("\n## Cross-Repo Dependencies\n");
    out.push_str("| Source Repo | Depends On | Via |\n");
    out.push_str("|---|---|---|\n");
    let mut dependency_rows = 0_usize;
    for repo_name in repo_names {
        for (target_repo, edge_kinds) in cross_repo_deps(graph, repo_name)? {
            let _ = writeln!(
                out,
                "| {} | {} | {} |",
                sanitize_table_cell(repo_name),
                sanitize_table_cell(&target_repo),
                // EdgeKind::to_string values are internal enum variants — literal.
                sanitize_table_cell(
                    &edge_kinds
                        .into_iter()
                        .map(|kind| kind.to_string())
                        .collect::<Vec<_>>()
                        .join(", ")
                )
            );
            dependency_rows += 1;
        }
    }
    if dependency_rows == 0 {
        out.push_str("| _No cross-repo dependencies detected_ | - | - |\n");
    }

    out.push_str("\n## Shared Symbols\n");
    out.push_str("| Symbol | Defined In | Used By |\n");
    out.push_str("|---|---|---|\n");
    let shared_symbols = limited_nodes(graph, NodeKind::SharedSymbol, DEFAULT_LIMIT)?;
    if shared_symbols.is_empty() {
        out.push_str("| _No shared symbols detected_ | - | - |\n");
    }
    for symbol in shared_symbols {
        let incoming = graph.get_incoming(symbol.id)?;
        let mut repos = incoming
            .into_iter()
            .filter_map(|edge| graph.get_node(edge.source).ok().flatten())
            .filter(|node| !node.is_virtual)
            .map(|node| node.repo)
            .collect::<BTreeSet<_>>();
        repos.remove(symbol.repo.as_str());
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            sanitize_table_cell(&symbol.name),
            sanitize_table_cell(&symbol.repo),
            if repos.is_empty() {
                "-".to_owned()
            } else {
                sanitize_table_cell(&repos.into_iter().collect::<Vec<_>>().join(", "))
            }
        );
    }

    out.push_str("\n## Conventions (Auto-Derived)\n");
    let conventions = derive_conventions(graph, registry, None)?;
    if conventions.is_empty() {
        out.push_str("- No conventions derived yet. Index more repos to infer patterns.\n");
    }
    for convention in conventions {
        let _ = writeln!(out, "- {convention}");
    }

    out.push_str("\n## Hotspot Warnings\n");
    out.push_str("| File | Repo | Churn Score | Bus Factor Risk |\n");
    out.push_str("|---|---|---:|---|\n");
    let mut hotspot_rows = 0_usize;
    if let Some(metadata) = metadata {
        let live_file_paths = repo_names
            .iter()
            .map(|repo| graph.nodes_by_repo(repo))
            .collect::<Result<Vec<_>, _>>()?
            .into_iter()
            .flatten()
            .filter(|node| node.kind == NodeKind::File)
            .map(|node| (node.repo, node.file_path))
            .collect::<BTreeSet<_>>();
        let mut hotspots = repo_names
            .iter()
            .map(|repo| metadata.list_file_analytics_for_repo(repo))
            .collect::<Result<Vec<_>, _>>()
            .map_err(ContextMdError::Metadata)?
            .into_iter()
            .flatten()
            .filter(|record| {
                live_file_paths.contains(&(record.repo.clone(), record.file_path.clone()))
            })
            .collect::<Vec<_>>();
        hotspots.sort_by(|left, right| {
            right
                .hotspot_score
                .total_cmp(&left.hotspot_score)
                .then_with(|| left.repo.cmp(&right.repo))
                .then_with(|| left.file_path.cmp(&right.file_path))
        });
        for record in hotspots.into_iter().take(DEFAULT_LIMIT) {
            let risk = if record.bus_factor <= 1 && record.top_owner_pct >= 0.7 {
                "high"
            } else if record.bus_factor <= 2 && record.top_owner_pct >= 0.5 {
                "medium"
            } else {
                "low"
            };
            let _ = writeln!(
                out,
                "| {} | {} | {:.2} | {} |",
                sanitize_table_cell(&record.file_path),
                sanitize_table_cell(&record.repo),
                record.hotspot_score,
                risk // literal — sanitization unnecessary
            );
            hotspot_rows += 1;
        }
    }
    if hotspot_rows == 0 {
        out.push_str("| _No hotspot analytics available yet_ | - | - | - |\n");
    }

    Ok(out)
}

fn render_events_rule(
    graph: &GraphStoreDb,
    repo_names: &[String],
) -> Result<String, ContextMdError> {
    let mut out = String::new();
    write_header(&mut out, "Events");
    out.push_str("# Event Surface\n\n");
    out.push_str("## Topics And Events\n");
    out.push_str("| Target | Producers | Consumers |\n");
    out.push_str("|---|---|---|\n");
    let targets = event_targets(graph, repo_names)?;
    if targets.is_empty() {
        out.push_str("| _No event or topic nodes detected_ | - | - |\n");
    }
    for target in targets.into_iter().take(DEFAULT_LIMIT) {
        let trace = trace_event(graph, target.id, DEFAULT_LIMIT)?;
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            sanitize_table_cell(&target.name),
            sanitize_table_cell(&summarize_matches(&trace.producers)),
            sanitize_table_cell(&summarize_matches(&trace.consumers)),
        );
    }

    out.push_str("\n## Orphans\n");
    out.push_str("| Target | Producers | Consumers | Classification |\n");
    out.push_str("|---|---:|---:|---|\n");
    let orphans = list_orphan_topics(
        graph,
        repo_names
            .first()
            .map(String::as_str)
            .filter(|_| repo_names.len() == 1),
        DEFAULT_LIMIT,
    )?;
    if orphans.is_empty() {
        out.push_str("| _No orphan topics detected_ | - | - | - |\n");
    }
    for orphan in orphans {
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} |",
            sanitize_table_cell(&orphan.target.name),
            orphan.producers, // numeric count — sanitization unnecessary
            orphan.consumers, // numeric count — sanitization unnecessary
            sanitize_table_cell(orphan.classification),
        );
    }

    Ok(out)
}

fn render_routes_rule(
    graph: &GraphStoreDb,
    repo_names: &[String],
) -> Result<String, ContextMdError> {
    let mut out = String::new();
    write_header(&mut out, "Routes");
    out.push_str("# Route Surface\n\n");
    out.push_str("| Route | Handler Repos | Caller Repos |\n");
    out.push_str("|---|---|---|\n");
    let routes = route_targets(graph, repo_names)?;
    if routes.is_empty() {
        out.push_str("| _No route nodes detected_ | - | - |\n");
    }
    for route in routes.into_iter().take(DEFAULT_LIMIT) {
        let trace = trace_route(graph, route.id, DEFAULT_LIMIT)?;
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            sanitize_table_cell(&route_name(&route)),
            sanitize_table_cell(&summarize_matches(&trace.handlers)),
            sanitize_table_cell(&summarize_matches(&trace.callers)),
        );
    }
    Ok(out)
}

fn render_repo_rule(
    graph: &GraphStoreDb,
    repo_name: &str,
    registered: &RegisteredRepo,
    workspace_root: Option<&std::path::Path>,
) -> Result<String, ContextMdError> {
    let mut out = String::new();
    write_header(&mut out, &format!("Repo {repo_name}"));
    let _ = writeln!(out, "# Repo Focus: {repo_name}\n");
    let path_display = match workspace_root {
        Some(root) => relativize_path_to_workspace(&registered.path, root),
        None => registered.path.display().to_string(),
    };
    let _ = writeln!(out, "Path: {}\n", wrap_inline_code(&path_display));
    out.push_str("## Summary\n");
    let _ = writeln!(
        out,
        "- Files indexed: {}\n- Symbols indexed: {}\n- Frameworks: {}\n- Depth: {}\n",
        registered.file_count,
        registered.symbol_count,
        if registered.frameworks.is_empty() {
            "-".to_owned()
        } else {
            registered.frameworks.join(", ")
        },
        depth_label(registered.depth_level),
    );

    out.push_str("## Cross-Repo Dependencies\n");
    let dependencies = cross_repo_deps(graph, repo_name)?;
    if dependencies.is_empty() {
        out.push_str("- No cross-repo dependencies detected.\n");
    }
    for (target_repo, kinds) in dependencies {
        let _ = writeln!(
            out,
            "- {} via {}",
            target_repo,
            kinds
                .into_iter()
                .map(|kind| kind.to_string())
                .collect::<Vec<_>>()
                .join(", ")
        );
    }

    out.push_str("\n## Event Targets\n");
    let event_targets = event_targets(graph, &[repo_name.to_owned()])?;
    if event_targets.is_empty() {
        out.push_str("- No event targets detected.\n");
    }
    for target in event_targets.into_iter().take(DEFAULT_LIMIT) {
        let _ = writeln!(out, "- {}", target.name);
    }

    Ok(out)
}

fn write_header(output: &mut String, section: &str) {
    output.push_str("<!-- AUTO-GENERATED by gather-step ");
    output.push_str(env!("CARGO_PKG_VERSION"));
    output.push_str(" -- do not edit manually -->\n");
    output.push_str("<!-- Regenerate with: gather-step generate claude-md -->\n");
    output.push_str("<!-- Last updated: ");
    output.push_str(&Utc::now().to_rfc3339_opts(SecondsFormat::Secs, true));
    output.push_str(" -->\n");
    output.push_str("<!-- Section: ");
    output.push_str(section);
    output.push_str(" -->\n\n");
}

fn selected_repo_names(registry: &WorkspaceRegistry, repo_filter: Option<&str>) -> Vec<String> {
    registry
        .repos
        .keys()
        .filter(|repo| repo_filter.is_none_or(|wanted| repo.as_str() == wanted))
        .cloned()
        .collect()
}

fn count_virtual_surfaces(
    graph: &GraphStoreDb,
    repo_name: &str,
) -> Result<(usize, usize), ContextMdError> {
    let mut routes = 0_usize;
    let mut topics = 0_usize;
    let repo_names = [repo_name.to_owned()];
    for node in graph.nodes_by_type(NodeKind::Route)? {
        if node.is_virtual && virtual_node_relevant_to_repos(graph, &node, &repo_names)? {
            routes += 1;
        }
    }
    for kind in [
        NodeKind::Topic,
        NodeKind::Queue,
        NodeKind::Subject,
        NodeKind::Stream,
        NodeKind::Event,
    ] {
        for node in graph.nodes_by_type(kind)? {
            if node.is_virtual && virtual_node_relevant_to_repos(graph, &node, &repo_names)? {
                topics += 1;
            }
        }
    }
    Ok((routes, topics))
}

fn virtual_node_relevant_to_repos(
    graph: &GraphStoreDb,
    node: &gather_step_core::NodeData,
    repo_names: &[String],
) -> Result<bool, ContextMdError> {
    let repos = repo_names
        .iter()
        .map(String::as_str)
        .collect::<BTreeSet<_>>();
    if repos.contains(node.repo.as_str()) {
        return Ok(true);
    }

    for edge in graph.get_incoming(node.id)? {
        if let Some(source) = graph.get_node(edge.source)?
            && !source.is_virtual
            && repos.contains(source.repo.as_str())
        {
            return Ok(true);
        }
    }

    Ok(false)
}

fn canonical_route_key(node: &gather_step_core::NodeData) -> Option<(String, String)> {
    let external_id = node
        .external_id
        .as_deref()
        .or(node.qualified_name.as_deref())?;
    let suffix = external_id
        .strip_prefix("__route__")
        .or_else(|| external_id.strip_prefix("__api_call__"))?;
    let (method, path) = suffix.split_once("__")?;
    let method = if method.eq_ignore_ascii_case("FETCH") {
        "GET".to_owned()
    } else {
        method.to_ascii_uppercase()
    };
    let path = if path.starts_with('/') {
        path.to_owned()
    } else {
        format!("/{path}")
    };
    Some((method, path))
}

fn route_priority(node: &gather_step_core::NodeData) -> u8 {
    match node.external_id.as_deref() {
        Some(id) if id.starts_with("__route__") => 0,
        Some(id) if id.starts_with("__api_call__") => 1,
        _ => 2,
    }
}

fn route_sort(left: &gather_step_core::NodeData, right: &gather_step_core::NodeData) -> Ordering {
    canonical_route_key(left)
        .cmp(&canonical_route_key(right))
        .then_with(|| route_priority(left).cmp(&route_priority(right)))
        .then_with(|| left.name.cmp(&right.name))
}

fn route_dedup_key(node: &gather_step_core::NodeData) -> String {
    canonical_route_key(node)
        .map(|(method, path)| format!("{method} {path}"))
        .or_else(|| node.external_id.clone())
        .or_else(|| node.qualified_name.clone())
        .unwrap_or_else(|| node.name.clone())
}

fn limited_nodes(
    graph: &GraphStoreDb,
    kind: NodeKind,
    limit: usize,
) -> Result<Vec<gather_step_core::NodeData>, ContextMdError> {
    let mut nodes = graph.nodes_by_type(kind)?;
    nodes.sort_by(|left, right| {
        left.repo
            .cmp(&right.repo)
            .then(left.file_path.cmp(&right.file_path))
            .then(left.name.cmp(&right.name))
    });
    if nodes.len() > limit {
        nodes.truncate(limit);
    }
    Ok(nodes)
}

fn event_targets(
    graph: &GraphStoreDb,
    repo_names: &[String],
) -> Result<Vec<gather_step_core::NodeData>, ContextMdError> {
    let mut targets = Vec::new();
    for kind in [
        NodeKind::Topic,
        NodeKind::Queue,
        NodeKind::Subject,
        NodeKind::Stream,
        NodeKind::Event,
    ] {
        for node in graph.nodes_by_type(kind)? {
            if node.is_virtual && virtual_node_relevant_to_repos(graph, &node, repo_names)? {
                targets.push(node);
            }
        }
    }
    targets.sort_by(|left, right| left.name.cmp(&right.name).then(left.repo.cmp(&right.repo)));
    targets.dedup_by_key(|node| node.id);
    Ok(targets)
}

fn route_targets(
    graph: &GraphStoreDb,
    repo_names: &[String],
) -> Result<Vec<gather_step_core::NodeData>, ContextMdError> {
    let mut routes = repo_names
        .iter()
        .map(|repo| graph.nodes_by_repo(repo))
        .collect::<Result<Vec<_>, _>>()?
        .into_iter()
        .flatten()
        .filter(|node| node.kind == NodeKind::Route && node.is_virtual)
        .collect::<Vec<_>>();
    routes.extend(
        graph
            .nodes_by_type(NodeKind::Route)?
            .into_iter()
            .filter(|node| node.is_virtual)
            .filter(|node| {
                virtual_node_relevant_to_repos(graph, node, repo_names).unwrap_or(false)
            }),
    );
    routes.sort_by(route_sort);
    routes.dedup_by_key(|node| route_dedup_key(node));
    Ok(routes)
}

fn summarize_matches(matches: &[gather_step_analysis::TopologyMatch]) -> String {
    let repos = matches
        .iter()
        .map(|item| item.repo.as_str())
        .collect::<BTreeSet<_>>();
    if repos.is_empty() {
        "-".to_owned()
    } else {
        repos.into_iter().collect::<Vec<_>>().join(", ")
    }
}

fn route_name(node: &gather_step_core::NodeData) -> String {
    canonical_route_key(node).map_or_else(
        || node.name.clone(),
        |(method, path)| format!("{method} {path}"),
    )
}

fn depth_label(depth: gather_step_core::DepthLevel) -> &'static str {
    match depth {
        gather_step_core::DepthLevel::Level1 => "level1",
        gather_step_core::DepthLevel::Level2 => "level2",
        gather_step_core::DepthLevel::Level3 => "level3",
        gather_step_core::DepthLevel::Full => "full",
        _ => "unknown",
    }
}

/// Render `path` relative to `workspace_root` for LLM-facing output.
///
/// Paths inside the workspace are returned as a relative string.  Paths that
/// resolve outside the workspace (or that cannot be stripped) are replaced with
/// the `"<outside-workspace>"` sentinel so the output never leaks absolute
/// filesystem layout.
///
/// # Examples
///
/// ```
/// use std::path::Path;
///
/// // The function is an internal helper; this documents the contract.
/// let root = Path::new("/workspace");
/// let abs  = Path::new("/workspace/service-a");
/// let rel  = abs.strip_prefix(root).map_or(
///     "<outside-workspace>".to_owned(),
///     |r| r.display().to_string(),
/// );
/// assert_eq!(rel, "service-a");
/// ```
fn relativize_path_to_workspace(
    path: &std::path::Path,
    workspace_root: &std::path::Path,
) -> String {
    path.strip_prefix(workspace_root).map_or_else(
        |_| "<outside-workspace>".to_owned(),
        |rel| rel.display().to_string(),
    )
}
